/** Shared Clerk theme — matches ConstructQA dark glass UI */
export const clerkAppearance = {
  variables: {
    colorPrimary: '#7c3aed',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    colorWarning: '#fbbf24',
    colorBackground: '#0d0d1f',
    colorInputBackground: '#1c1c3a',
    colorInputText: '#f8fafc',
    colorText: '#f8fafc',
    colorTextSecondary: '#cbd5e1',
    colorTextOnPrimaryBackground: '#ffffff',
    colorNeutral: '#94a3b8',
    borderRadius: '0.75rem',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: '14px',
    spacingUnit: '0.5rem',
  },
  elements: {
    rootBox: 'clerk-root-box',
    cardBox: 'clerk-card-box',
    card: 'clerk-card',
    header: 'clerk-header',
    headerTitle: 'clerk-header-title',
    headerSubtitle: 'clerk-header-subtitle',
    socialButtons: 'clerk-social-buttons',
    socialButtonsBlockButton: 'clerk-social-btn',
    socialButtonsBlockButtonIcon: 'clerk-social-btn-icon',
    socialButtonsBlockButtonText: 'clerk-social-btn-text',
    dividerLine: 'clerk-divider-line',
    dividerText: 'clerk-divider-text',
    formFieldLabel: 'clerk-label',
    formFieldInput: 'clerk-input',
    otpCodeField: 'clerk-otp-field',
    otpCodeFieldInputs: 'clerk-otp-inputs',
    otpCodeFieldInput: 'clerk-otp-box',
    otpCodeFieldInputContainer: 'clerk-otp-container',
    formFieldErrorText: 'clerk-field-error',
    formFieldError: 'clerk-field-error-row',
    formFieldSuccessText: 'clerk-field-success',
    formFieldHintText: 'clerk-field-hint',
    formButtonPrimary: 'clerk-btn-primary',
    footerActionText: 'clerk-footer-text',
    footerActionLink: 'clerk-link',
    identityPreviewText: 'clerk-identity-text',
    identityPreviewEditButton: 'clerk-link',
    formFieldInputShowPasswordButton: 'clerk-link',
    alert: 'clerk-alert',
    alertText: 'clerk-alert-text',
    footer: 'clerk-footer',
    logoBox: 'clerk-logo-hidden',
    logoImage: 'clerk-logo-hidden',
    userButtonPopoverCard: 'clerk-user-popover',
    userButtonPopoverMain: 'clerk-user-popover-main',
    userPreview: 'clerk-user-preview',
    userPreviewMainIdentifier: 'clerk-user-name',
    userPreviewSecondaryIdentifier: 'clerk-user-email',
    userButtonPopoverActionButton: 'clerk-user-menu-btn',
    userButtonPopoverActionButtonIcon: 'clerk-user-menu-icon',
    userButtonPopoverActionButtonText: 'clerk-user-menu-text',
    userButtonPopoverFooter: 'clerk-user-popover-footer',
    menuList: 'clerk-user-menu-list',
    menuItem: 'clerk-user-menu-item',
    userProfile: 'clerk-user-profile',
    userProfilePage: 'clerk-user-profile-page',
    navbar: 'clerk-profile-navbar',
    navbarButton: 'clerk-profile-nav-btn',
    navbarButtonIcon: 'clerk-profile-nav-icon',
    navbarButtonText: 'clerk-profile-nav-text',
    profilePage: 'clerk-profile-page',
    profileSection: 'clerk-profile-section',
    profileSectionTitle: 'clerk-profile-section-title',
    profileSectionTitleText: 'clerk-profile-section-title-text',
    profileSectionContent: 'clerk-profile-section-content',
    profileSectionPrimaryButton: 'clerk-profile-section-btn',
    badge: 'clerk-profile-badge',
    identityPreview: 'clerk-profile-identity',
    accordionTriggerButton: 'clerk-profile-accordion-btn',
    modalBackdrop: 'clerk-modal-backdrop',
    modalContent: 'clerk-modal-content',
  },
  layout: {
    /** Email + password fields appear before Google on sign-in */
    socialButtonsPlacement: 'bottom',
    showOptionalFields: true,
  },
}
