/** Shared Clerk theme — matches ConstructQA dark glass UI */
export const clerkAppearance = {
  variables: {
    colorPrimary: '#7c3aed',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    colorWarning: '#fbbf24',
    colorBackground: '#0d0d1f',
    colorInputBackground: '#12122a',
    colorInputText: '#f1f5f9',
    colorText: '#f1f5f9',
    colorTextSecondary: '#94a3b8',
    colorTextOnPrimaryBackground: '#ffffff',
    colorNeutral: '#64748b',
    borderRadius: '0.75rem',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: '14px',
    spacingUnit: '0.9rem',
  },
  elements: {
    rootBox: 'clerk-root-box',
    cardBox: 'clerk-card-box',
    card: 'clerk-card',
    header: 'clerk-header',
    headerTitle: 'clerk-header-title',
    headerSubtitle: 'clerk-header-subtitle',
    socialButtons: 'clerk-social-buttons',
    socialButtonsBlockButton: 'clerk-social-btn',
    socialButtonsBlockButtonText: 'clerk-social-btn-text',
    dividerLine: 'clerk-divider-line',
    dividerText: 'clerk-divider-text',
    formFieldLabel: 'clerk-label',
    formFieldInput: 'clerk-input',
    formButtonPrimary: 'clerk-btn-primary',
    footerActionText: 'clerk-footer-text',
    footerActionLink: 'clerk-link',
    identityPreviewText: 'clerk-identity-text',
    identityPreviewEditButton: 'clerk-link',
    formFieldInputShowPasswordButton: 'clerk-link',
    alert: 'clerk-alert',
    alertText: 'clerk-alert-text',
    footer: 'clerk-footer',
    logoBox: 'clerk-logo-hidden',
    logoImage: 'clerk-logo-hidden',
  },
  layout: {
    socialButtonsPlacement: 'top',
    showOptionalFields: true,
  },
}
